version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    depends_on: 
      - zookeeper
    links: 
      - zookeeper
    ports:
      - 9092:9092
    environment: 
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.109:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/data:/var/lib/mysql
  # MySQL 的 Web 客户端
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 7070:8080
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  runway-airport:
    image: youzidata/apptemplate
    container_name: runway-airport
    restart: always
    depends_on: 
      - redis
      - mysql
      - kafka
    volumes: 
      - /usr/local/java/runway-airport-0.0.1-SNAPSHOT.jar:/usr/local/java/app.jar
      - /usr/local/java/logs:/script/logs
    ports: 
      - 8081:8081 
  nginx:
    image: nginx
    container_naem: nginx
    restart: always
    volumes:
      - /usr/local/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/nginx/static:/opt
    ports:
      - 443:443
      - 80:80
      - 81:81
      - 82:81
      - 83:83
      - 84:84
      - 85:85
      